#pragma once
void closeSafe();
void closeDisrupt();
void farSafe();
void skills();
void ace();
void trustAlliance();
void driverStart();
void farRush();
void default_constants();
void exit_condition_defaults();
